spring:
  profiles:
    active: dev
  application:
    name: ifc2rdf-service
server:
  port: 8322

mybatis:
  type-aliases-package: com.jz.platform.dal
  mapper-locations: classpath*:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.100.49.31:16603/cloud_render?useUnicode=true&characterEncoding=utf8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: dbpass

logging:
  level:
    org.springframework.boot: DEBUG
    com.jz.platform.dao: DEBUG
  file:
    path: e:/Temp/ifc2rdf/logs

app:
  ifc-path: e:/Temp/ifc2rdf/
  jena-fusiki:
    host: 127.0.0.1
    port: 3030
